name: claire-hamilton-website
region: nyc

# Static site (Frontend)
static_sites:
  - name: frontend
    github:
      repo: AntonyNeal/sw_website
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_GA_MEASUREMENT_ID
        value: ${GA_MEASUREMENT_ID}
      - key: VITE_API_BASE_URL
        value: ${API_BASE_URL}
      - key: VITE_FUNCTIONS_URL
        value: ${FUNCTIONS_URL}
    routes:
      - path: /
