name: octopus-app
region: syd

# API Service (Backend - Express API)
services:
  - name: api
    github:
      repo: AntonyNeal/sw_website
      branch: main
      deploy_on_push: true
    source_dir: /api
    build_command: npm install
    run_command: node server.js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: DB_HOST
        scope: RUN_TIME
      - key: DB_PORT
        scope: RUN_TIME
      - key: DB_NAME
        scope: RUN_TIME
      - key: DB_USER
        scope: RUN_TIME
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_SSL
        scope: RUN_TIME
        value: require
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: '8080'
    routes:
      - path: /api

  # Web Service (Frontend - React SPA)
  - name: sw-website
    github:
      repo: AntonyNeal/sw_website
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npx http-server ./dist -p 8080 -c-1 --proxy https://octopus-app-s8m2n.ondigitalocean.app?
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: VITE_API_BASE_URL
        value: https://clairehamilton.vip/api
    routes:
      - path: /

# Domain configuration
domains:
  - domain: clairehamilton.vip
    type: PRIMARY
  - domain: www.clairehamilton.vip
    type: ALIAS
  - domain: avaliable.pro
    type: ALIAS
    wildcard: true
